# Generated by Django 5.2.8 on 2025-11-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_joined_date_member_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='amd_intel',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='music_favorite',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='video_gaeme_fevorite',
            field=models.BooleanField(null=True),
        ),
    ]
