# Generated by Django 5.2.8 on 2025-11-14 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_member_amd_intel_member_music_favorite_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='video_gaeme_fevorite',
            new_name='video_game_favorite',
        ),
    ]
