# Generated by Django 5.2.8 on 2025-11-25 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_rename_video_gaeme_fevorite_member_video_game_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='amd_intel',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='member',
            name='music_favorite',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='member',
            name='video_game_favorite',
            field=models.CharField(max_length=100),
        ),
    ]
